import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useLocation } from "wouter";
import { BookOpen, Brain, ChevronLeft, ClipboardList, Gauge, Command as CommandIcon, MessageCircle, Search, Settings2, StickyNote, UsersRound } from "lucide-react";
import { CustomliLogo } from "@/components/customli-logo";
import "./sidebar-accordion.css"; import "./ui-cleanup.css"; import "./page-consistency.css"; import "./header-icon-policy.css"; import "./employee-factory-nav.css";
type NavItem = { href: string; label: string; icon: React.ComponentType<{ className?: string }> };
export function Layout({ children }: { children: React.ReactNode }) {
 const [location] = useLocation(); const [isCollapsed,setIsCollapsed]=useState(()=>typeof window!=="undefined"&&window.matchMedia("(max-width: 1180px)").matches); const [query,setQuery]=useState(""); const [paletteOpen,setPaletteOpen]=useState(false); const searchRef=useRef<HTMLInputElement>(null);
 const navItems: NavItem[] = [
   { href: "/", label: "Dashboard", icon: Gauge },
   { href: "/james", label: "Talk to James", icon: MessageCircle },
   { href: "/notes", label: "Notes", icon: StickyNote },
   { href: "/tasks", label: "Tasks", icon: ClipboardList },
   { href: "/team", label: "AI Team", icon: UsersRound },
   { href: "/brain", label: "Mission Brain", icon: Brain },
   { href: "/skills", label: "Skills", icon: BookOpen },
   { href: "/settings", label: "Settings", icon: Settings2 },
 ];
 const normalizedQuery=query.trim().toLowerCase(); const visibleNavItems=useMemo(()=>navItems.filter(i=>i.label.toLowerCase().includes(normalizedQuery)),[normalizedQuery]);
 useEffect(()=>{const q=window.matchMedia("(max-width: 1180px)"); const sync=(e:MediaQueryListEvent)=>setIsCollapsed(e.matches); q.addEventListener("change",sync); return()=>q.removeEventListener("change",sync)},[]);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="f"){e.preventDefault();if(isCollapsed)setIsCollapsed(false);window.setTimeout(()=>searchRef.current?.focus(),0)}};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h)},[isCollapsed]);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPaletteOpen(v=>!v)}if(e.key==="Escape")setPaletteOpen(false)};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h)},[]);
 function renderNavItem(item:NavItem){const active=location===item.href||(item.href!=="/"&&location.startsWith(item.href));const Icon=item.icon;return <Link key={`${item.href}-${item.label}`} href={item.href} title={isCollapsed?item.label:undefined} aria-label={item.label} className={`mission-nav-item ${active?"mission-nav-active":""}`}><Icon className="mission-nav-icon" />{!isCollapsed&&<span>{item.label}</span>}</Link>}
 const routeClass=location==="/"?"dashboard":location.split("/")[1]||"dashboard";
 return <div className="mission-app-bg relative min-h-screen overflow-hidden flex text-foreground"><div className="mission-premium-background" aria-hidden="true"/><aside className={`mission-sidebar relative z-10 flex-shrink-0 flex flex-col ${isCollapsed?"mission-sidebar-collapsed":"mission-sidebar-expanded"}`}><div className="mission-sidebar-top"><CustomliLogo compact={isCollapsed}/></div>{!isCollapsed&&<label className="mission-sidebar-search"><Search aria-hidden="true"/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search menu" aria-label="Search navigation"/></label>}<nav className="mission-sidebar-nav" aria-label="Main navigation"><ul>{visibleNavItems.map(i=><li key={i.href}>{renderNavItem(i)}</li>)}</ul>{!isCollapsed&&visibleNavItems.length===0&&<p className="mission-nav-empty">No menu matches “{query}”.</p>}</nav><div className="mission-sidebar-toggle-dock"><button type="button" className="mission-collapse-button" aria-label="Open command palette" title="Open command palette" onClick={()=>setPaletteOpen(true)}><CommandIcon aria-hidden="true"/></button><button type="button" className="mission-collapse-button mission-collapse-button-bottom" onClick={()=>setIsCollapsed(v=>!v)} aria-label={isCollapsed?"Open sidebar":"Close sidebar"} aria-expanded={!isCollapsed} title={isCollapsed?"Open sidebar":"Close sidebar"}><ChevronLeft aria-hidden="true"/></button></div></aside><main className={`mission-main-canvas mission-route-${routeClass} relative z-10 flex-1 flex flex-col h-screen overflow-hidden bg-transparent`}>{children}</main>{paletteOpen&&<div className="fixed inset-0 z-50 grid place-items-start bg-black/60 p-4 pt-[10vh]" role="dialog" aria-modal="true" aria-label="Mission Control commands" onMouseDown={()=>setPaletteOpen(false)}><div className="mx-auto w-full max-w-xl rounded-xl border border-border bg-card p-3 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="mb-2 flex items-center justify-between"><strong>Mission Control</strong><button onClick={()=>setPaletteOpen(false)} aria-label="Close command palette">Close</button></div><div className="grid gap-1">{[["Talk to James","/james"],["Hire AI Employee","/team?hire=1"],["Add Note","/notes?create=note"],["Add Idea","/notes?create=idea"],["Add Task","/tasks?create=task"],["Search Mission Control","/brain/executions"],["Search Memory","/brain"],["Open Mission Brain","/brain"],["Open Project or Repository","/workspaces"],["Task approvals & review","/tasks"],["Open Agent","/agent-operations"],["View Running or Failed Work","/brain/executions"],["Skills and Playbooks","/skills"],["Signals","/signals"]].map(([label,href])=><Link key={label} href={href} onClick={()=>setPaletteOpen(false)} className="rounded-lg px-3 py-2 text-sm hover:bg-secondary">{label}</Link>)}</div></div></div>}</div>;
}
