import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import tasksRouter from "./tasks";
import taskAttachmentsRouter from "./task-attachments";
import contentRouter from "./content";
import eventsRouter from "./events";
import memoriesRouter from "./memories";
import agentsRouter from "./agents";
import contactsRouter from "./contacts";
import activityRouter from "./activity";
import integrationsRouter from "./integrations";
import toolsRouter from "./tools";
import agentBridgeRouter from "./agent-bridge";
import jamesRouter from "./james";
import jamesDetachedRouter from "./james-detached";
import worktreesRouter from "./worktrees";
import skillsRouter from "./skills";
import orchestratorRouter from "./orchestrator";
import executionsRouter from "./executions";
import intelligenceRouter from "./intelligence";
import operationsRouter from "./operations";
import { requireAdminAuth } from "../lib/auth.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/agents/:id/dispatch", requireAdminAuth);
router.use("/agents/:id/token", requireAdminAuth);
router.use("/agents/:id/test", requireAdminAuth);
router.use("/agents/:id/test-task", requireAdminAuth);
router.use(agentBridgeRouter);
router.use(requireAdminAuth);
router.use(dashboardRouter);
router.use(jamesRouter);
router.use(jamesDetachedRouter);
router.use(worktreesRouter);
router.use(skillsRouter);
router.use(orchestratorRouter);
router.use(executionsRouter);
router.use(intelligenceRouter);
router.use(operationsRouter);
router.use(taskAttachmentsRouter);
router.use(tasksRouter);
router.use(contentRouter);
router.use(eventsRouter);
router.use(memoriesRouter);
router.use(agentsRouter);
router.use(contactsRouter);
router.use(activityRouter);
router.use(integrationsRouter);
router.use(toolsRouter);

export default router;
