import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import tasksRouter from "./tasks";
import taskListCompatRouter from "./task-list-compat";
import kanbanStatusCompatRouter from "./kanban-status-compat";
import taskAttachmentsRouter from "./task-attachments";
import contentRouter from "./content";
import eventsRouter from "./events";
import memoriesRouter from "./memories";
import agentsRouter from "./agents";
import contactsRouter from "./contacts";
import activityRouter from "./activity";
import integrationsRouter from "./integrations";
import toolsRouter from "./tools";
import agentSkillsRouter from "./agent-skills";
import agentBridgeRouter from "./agent-bridge";
import jamesNativeVoiceBridgeRouter from "./james-native-voice-bridge";
import jamesRouter from "./james";
import jamesDetachedRouter from "./james-detached";
import workerSupervisionRouter from "./worker-supervision";
import worktreesRouter from "./worktrees";
import skillsRouter from "./skills";
import orchestratorRouter from "./orchestrator";
import capabilityRoutingRouter from "./capability-routing";
import executionsRouter from "./executions";
import intelligenceRouter from "./intelligence";
import intelligenceAnalystRouter from "./intelligence-analyst";
import operationsRouter from "./operations";
import inboxRouter from "./inbox";
import provisioningRouter from "./provisioning";
import employeeFactoryRouter from "./employee-factory";
import agentProfileRouter from "./agent-profile";
import amandaCertificationRouter from "./amanda-certification";
import modelPolicyRouter from "./model-policy";
import { requireAdminAuth } from "../lib/auth.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/agents/:id/dispatch", requireAdminAuth);
router.use("/agents/:id/token", requireAdminAuth);
router.use("/agents/:id/test", requireAdminAuth);
router.use("/agents/:id/test-task", requireAdminAuth);
router.use(agentSkillsRouter);
router.use(agentBridgeRouter);
router.use(requireAdminAuth);
router.use(dashboardRouter);
router.use(jamesNativeVoiceBridgeRouter);
router.use(jamesRouter);
router.use(jamesDetachedRouter);
router.use(workerSupervisionRouter);
router.use(worktreesRouter);
router.use(skillsRouter);
router.use(orchestratorRouter);
router.use(capabilityRoutingRouter);
router.use(executionsRouter);
router.use(intelligenceRouter);
router.use(intelligenceAnalystRouter);
router.use(operationsRouter);
router.use(inboxRouter);
router.use(modelPolicyRouter);
router.use(amandaCertificationRouter);
router.use(agentProfileRouter);
router.use(employeeFactoryRouter);
router.use(provisioningRouter);
router.use(taskAttachmentsRouter);
router.use(taskListCompatRouter);
router.use(kanbanStatusCompatRouter);
router.use(tasksRouter);
router.use(contentRouter);
router.use(eventsRouter);
router.use(memoriesRouter);
router.use(agentsRouter);
router.use(contactsRouter);
router.use(activityRouter);
router.use(integrationsRouter);
router.use(toolsRouter);

export default router;