import type { agentsTable } from "@workspace/db";

type PublicAgent = Omit<typeof agentsTable.$inferSelect, "apiKey" | "createdAt"> & {
  apiKeyHint: null;
  assignedSkills: string[];
};

export const OPERATIONAL_AGENTS: PublicAgent[] = [
  {
    id: -1,
    name: "James",
    role: "Orchestrator",
    department: "Operators",
    isLead: true,
    status: "active",
    currentTask: "Current assigned orchestrator",
    lastActive: "current",
    responsibilities: "Coordinates plans, workspace context, permissions, and chat handoff.",
    avatarInitials: "JA",
    tasksCompleted: 0,
    successRate: 100,
    isPluggedIn: true,
    provider: null,
    model: null,
    endpoint: "/api/james/message",
    inboundToken: null,
    lastPing: null,
    apiKeyHint: null,
    assignedSkills: ["orchestration"],
  },
  {
    id: -2,
    name: "Scout",
    role: "Research",
    department: "Researchers",
    isLead: false,
    status: "idle",
    currentTask: "Available / not active",
    lastActive: "not active",
    responsibilities: "Source-backed research and structured briefs.",
    avatarInitials: "SC",
    tasksCompleted: 0,
    successRate: 100,
    isPluggedIn: false,
    provider: null,
    model: null,
    endpoint: null,
    inboundToken: null,
    lastPing: null,
    apiKeyHint: null,
    assignedSkills: [],
  },
  {
    id: -3,
    name: "Scribe",
    role: "Documentation/content",
    department: "Writers",
    isLead: false,
    status: "idle",
    currentTask: "Available / not active",
    lastActive: "not active",
    responsibilities: "Validated notes, docs, and content drafts.",
    avatarInitials: "SR",
    tasksCompleted: 0,
    successRate: 100,
    isPluggedIn: false,
    provider: null,
    model: null,
    endpoint: null,
    inboundToken: null,
    lastPing: null,
    apiKeyHint: null,
    assignedSkills: [],
  },
  {
    id: -4,
    name: "Reach",
    role: "Marketing/outreach",
    department: "Operators",
    isLead: false,
    status: "idle",
    currentTask: "Available / not active",
    lastActive: "not active",
    responsibilities: "Approved audience and outreach materials.",
    avatarInitials: "RE",
    tasksCompleted: 0,
    successRate: 100,
    isPluggedIn: false,
    provider: null,
    model: null,
    endpoint: null,
    inboundToken: null,
    lastPing: null,
    apiKeyHint: null,
    assignedSkills: [],
  },
  {
    id: -5,
    name: "Dev/Codex",
    role: "Build agent",
    department: "Developers",
    isLead: false,
    status: "idle",
    currentTask: "Available / not active",
    lastActive: "not active",
    responsibilities: "Scoped implementation after explicit plans are approved.",
    avatarInitials: "DC",
    tasksCompleted: 0,
    successRate: 100,
    isPluggedIn: false,
    provider: null,
    model: null,
    endpoint: null,
    inboundToken: null,
    lastPing: null,
    apiKeyHint: null,
    assignedSkills: [],
  },
  {
    id: -6,
    name: "OpenClaw / Bob",
    role: "Orchestrator candidate",
    department: "Operators",
    isLead: false,
    status: "idle",
    currentTask: "Available / not active",
    lastActive: "not active",
    responsibilities: "Can be assigned as orchestrator later.",
    avatarInitials: "OB",
    tasksCompleted: 0,
    successRate: 100,
    isPluggedIn: false,
    provider: null,
    model: null,
    endpoint: null,
    inboundToken: null,
    lastPing: null,
    apiKeyHint: null,
    assignedSkills: [],
  },
];

export const CURRENT_ORCHESTRATOR_NAME = "James";


const CONFIGURED_AGENT_SKILLS: Record<string, string[]> = {
  james: ["orchestration"],
  "dev/codex": ["coding"],
  codex: ["coding"],
  gemini: [],
  claude: [],
  openclaw: [],
  "openclaw / bob": [],
};

export function getAssignedSkillNamesForAgent(agentName: string): string[] {
  return CONFIGURED_AGENT_SKILLS[agentName.toLowerCase()] ?? [];
}
